-- Baseline: esquema tal y como lo dejaba spring.jpa.hibernate.ddl-auto=update
-- antes de adoptar Flyway. No editar.

create table if not exists app_user (
    id         bigint generated by default as identity primary key,
    created_at timestamp(6),
    email      varchar(255) not null,
    enabled    boolean      not null,
    password   varchar(255) not null,
    updated_at timestamp(6),
    username   varchar(50)  not null,
    constraint uk_app_user_email    unique (email),
    constraint uk_app_user_username unique (username)
);

create table if not exists task (
    id          bigint generated by default as identity primary key,
    completed   boolean     not null,
    created_at  timestamp(6),
    description varchar(4000),
    due_date    date,
    priority    varchar(255) check (priority in ('LOW', 'MEDIUM', 'HIGH')),
    sort_order  integer,
    title       varchar(500) not null,
    updated_at  timestamp(6),
    user_id     bigint
);

create table if not exists user_roles (
    user_id bigint      not null,
    role    varchar(255),
    constraint fk_user_roles_user foreign key (user_id) references app_user (id)
);